apiVersion: v2
description: common
type: application
name: common
version: 2.2.2
appVersion: 4.0.0
kubeVersion: '>=1.17.0-0'
dependencies:
  - name: common
    version: 4.0.1
    repository: https://library-charts.k8s-at-home.com
    import-values:
      - child: addons
        parent: addons
