annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Add presence options and update to dendrite v0.8.1
apiVersion: v2
appVersion: v0.8.1
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - condition: postgresql.enabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 11.1.15
  - condition: nats.enabled
    name: nats
    repository: https://nats-io.github.io/k8s/helm/charts/
    version: 0.16.0
  - alias: clientapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: mediaapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: syncapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: roomserver
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: eduserver
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: federationapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: keyserver
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: userapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
  - alias: appserviceapi
    condition: dendrite.polylithEnabled
    name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.3.0
description: Dendrite Matrix Homeserver
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/dendrite
keywords:
  - dendrite
  - matrix
  - homeserver
  - monolith
  - federation
  - polylith
kubeVersion: '>=1.16.0-0'
maintainers:
  - email: jonathan@jonnobrow.co.uk
    name: jonnobrow
name: dendrite
sources:
  - https://github.com/matrix-org/dendrite
  - https://github.com/matrix-org/dendrite/tree/master/build/docker
version: 4.1.0
