apiVersion: v2
appVersion: v0.8.9
description: Dendrite Matrix Homeserver
name: dendrite
version: 6.0.2
kubeVersion: '>=1.16.0-0'
keywords:
  - dendrite
  - matrix
  - homeserver
  - monolith
  - federation
  - polylith
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/dendrite
sources:
  - https://github.com/matrix-org/dendrite
  - https://github.com/matrix-org/dendrite/tree/master/build/docker
maintainers:
  - name: jonnobrow
    email: jonathan@jonnobrow.co.uk
dependencies:
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
  - name: postgresql
    version: 11.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: nats
    version: 0.17.5
    repository: https://nats-io.github.io/k8s/helm/charts/
    condition: nats.enabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: clientapi
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: mediaapi
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: syncapi
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: roomserver
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: federationapi
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: keyserver
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: userapi
    condition: dendrite.polylithEnabled
  - name: common
    repository: https://library-charts.k8s-at-home.com
    version: 4.5.2
    alias: appserviceapi
    condition: dendrite.polylithEnabled
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `dendrite` dependency to version 0.8.9
    - kind: added
      description: Added ingress for polylith mode
    - kind: changed
      description: "**Breaking**: Updated default config as per separate monolith/polylith samples"
